<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>yan_pkg</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="22920242203465@stu.xmu.edu.cn">chloe</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- 在运行时的依赖库，这里我们只用到了rclcpp -->
  <!-- 目前只有这一行是我们自己添的，其他都是create pkg自动生成的 -->
  <depend>rclcpp</depend> <!-- ROS 2 C++ 客户端库 -->

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
